#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

banner "WDZA Stats: Railway deployment"

# ── Stage 1: log in ────────────────────────────────────────────────────────
stage "Railway login"
say "This links the Railway CLI to your account via browser OAuth."
railway login
if ! railway whoami >/dev/null 2>&1; then
  warn "not logged in yet - re-run this script once 'railway login' succeeds."
  exit 1
fi
say "Logged in as: $(railway whoami)"

# ── Stage 2: create + link the project ─────────────────────────────────────
stage "Create the Railway project"
say "Creating a new Railway project and linking this directory to it."
railway init -n wdza-stats
railway status || true

# ── Stage 3: add Postgres ──────────────────────────────────────────────────
stage "Add PostgreSQL"
say "Provisioning a Postgres database service shared by both apps."
railway add -d postgres
step "Opening the project dashboard - confirm the exact name of the Postgres"
step "service there (usually 'Postgres'); you'll need it for variable references."
railway open || true
ask POSTGRES_SERVICE_NAME "Exact Postgres service name shown in the dashboard:"
write_env POSTGRES_SERVICE_NAME "$POSTGRES_SERVICE_NAME"

# ── Stage 4: create the two empty services ─────────────────────────────────
stage "Create the worker and web services"
say "Creating two empty services - we deploy code into them from the CLI later."
railway add -s worker
railway add -s web

# ── Stage 5: configure the worker service ──────────────────────────────────
stage "Configure the worker service"
warn "The RCON token used during design/discovery was shared in plaintext chat"
warn "and must be treated as compromised. Rotate it on the game server first"
warn "(WardogsServer -GenerateRCONHash=<new-password>, or a new Password= in"
warn "ServerSettings.ini) and enter the NEW value below - never the old one."
say "This project's ServerSettings.ini reference lives in CONTEXT.md / the RCON docs."
current_server_name=$(_existing SERVER_NAME || true)
current_base_url=$(_existing RCON_BASE_URL || true)
ask SERVER_NAME "WDZA server display name${current_server_name:+ [Enter keeps current]}:"
ask RCON_BASE_URL "RCON base URL, e.g. https://host:9006${current_base_url:+ [Enter keeps current]}:"
ask_secret RCON_TOKEN "NEW (rotated) RCON bearer token:"
write_env SERVER_NAME "$SERVER_NAME"
write_env RCON_BASE_URL "$RCON_BASE_URL"
railway variable set "SERVER_NAME=$SERVER_NAME" -s worker
railway variable set "RCON_BASE_URL=$RCON_BASE_URL" -s worker
railway variable set "RCON_TOKEN=$RCON_TOKEN" -s worker
railway variable set "DATABASE_URL="'${{'"$POSTGRES_SERVICE_NAME"'.DATABASE_URL}}' -s worker
note "worker variables set: SERVER_NAME, RCON_BASE_URL, RCON_TOKEN, DATABASE_URL"
say "Now open the worker service -> Settings in the dashboard and paste in:"
step "Build Command:  $(python3 -c "import json;print(json.load(open('railway.worker.json'))['build']['buildCommand'])")"
step "Start Command:  $(python3 -c "import json;print(json.load(open('railway.worker.json'))['deploy']['startCommand'])")"
pause "Press Enter once the worker's Build/Start commands are saved."

# ── Stage 6: configure the web service ─────────────────────────────────────
stage "Configure the web service"
railway variable set "DATABASE_URL="'${{'"$POSTGRES_SERVICE_NAME"'.DATABASE_URL}}' -s web
note "web variable set: DATABASE_URL"
say "Now open the web service -> Settings in the dashboard and paste in:"
step "Build Command:       $(python3 -c "import json;print(json.load(open('railway.web.json'))['build']['buildCommand'])")"
step "Start Command:       $(python3 -c "import json;print(json.load(open('railway.web.json'))['deploy']['startCommand'])")"
step "Healthcheck Path:    $(python3 -c "import json;print(json.load(open('railway.web.json'))['deploy']['healthcheckPath'])")"
pause "Press Enter once the web service's settings are saved."

# ── Stage 7: deploy both services ──────────────────────────────────────────
stage "Deploy"
say "Uploading and building the worker service (this repo's full monorepo context)."
railway up -s worker --ci
say "Uploading and building the web service."
railway up -s web --ci

# ── Stage 8: verify ─────────────────────────────────────────────────────────
stage "Verify"
say "Generating a public domain for the web service..."
railway domain -s web || true
WEB_URL=$(_existing WEB_URL || true)
ask WEB_URL "Paste the web service's URL shown above (https://...):"
write_env WEB_URL "$WEB_URL"
say "Checking /api/health..."
curl -sS "${WEB_URL%/}/api/health" || warn "health check request failed - check the URL and try again"
printf '\n'
say "Worker's last 20 log lines (look for the heartbeat line):"
railway logs -s worker --lines 20 || true
# ──────────────────────────────────────────────────────────────────────────

finish
note "Ticket 02 replaces the worker's heartbeat loop with real RCON polling -"
note "no further Railway setup should be needed for that."
